builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - solaris
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256-checksums.txt"

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
