builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  algorithm: sha512

release:
  prerelease: auto
