language: go
go:
  - 1.12.x

install:
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/jgautheron/goconst/cmd/goconst
  - go get github.com/gordonklaus/ineffassign
  - dep ensure

script:
  - golint -set_exit_status $(go list ./...)
  - errcheck ./...
  - goconst -ignore=^vendor ./...
  - ineffassign ./

before_script:
  - echo "REPO ${TRAVIS_REPO_SLUG} TAG ${TRAVIS_TAG}"
