language: minimal

services:
  - docker

install:
  - docker build -t sensu-sic-handler .
  - export CONTAINER_ID="$(docker run -d -e GITHUB_TOKEN -v $(pwd):/go/src/sensu-sic-handler sensu-sic-handler sleep 3600)"
  - docker exec ${CONTAINER_ID} sh -c 'dep ensure'

before_script:
  - echo "REPO ${TRAVIS_REPO_SLUG} TAG ${TRAVIS_TAG}"

script:
  - docker exec ${CONTAINER_ID} sh -c 'golangci-lint run -E gofmt -E gosec -E dupl -E goconst -E gocritic -E lll -E maligned -E misspell -E nakedret -E prealloc -E scopelint -E unconvert -E unparam'

deploy:
  provider: script
  script: docker exec ${CONTAINER_ID} sh -c 'goreleaser'
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    secure: "iiHyfMMq9ovS9xstBR6z/h0hkAKreCtuGRKCcLFFEktB2FwC7C7bBkb1w1gLJfye7yqLX25KGt7is8BEhyUDLe9kUJiStceGgMDom1yWYd+qM1Ae8ijgkhTiDJMFsBpuOZBa6UpUWuWLENamSX84oP+ykO5nmNelg4+ed4LpixI7i2I6LYmyPCtuSpn077uIuZMzEvQ07EPP7EUCK5iSkgweVsBeFIZVZ0D/Pviiwbcvo4kYpBHBJVMnVT0C8GYo6jmuHFYxxoF4RIULmxLzwsJGKOAUVejKfhuselWhgPim8r8EMVgoPq9e249Ev1rlsopKj/MA7Mu6lsStMqCEkIi1VprHGLWWpSuIpBllq26yx5+3XND7x8oG6AS7Ieq8RBjf8q4VuYYJCBgV7yeMhirbBZXuoJryZJEVx6PH6vEH2zWSIVWn4Iu7NEuI3rvTi+kTf/US/IzC/6HQ7Vft1c4PrKNrJlOf+ai7JL6EId1pfq/BM30ecjk/Kb2JWZDe9L4mRy+bRRsMecVWhVcUDD1VLWPyx7aQ4rZTc3hNIV4Lr1tshmvrupTVihpHFiVXEa7SGEThI8t2Yn+EWMulYX9Db4NQr/NYqsfPjQicwsHS4IjX7L5VF8n39APduiksuq35o8hd4eR6E/bBrVjiMxnSbu9eadzamyEtf7SbOJk="
