language: minimal

services:
  - docker

install:
  - docker build -t sensu-sic-handler .
  - export CONTAINER_ID="$(docker run -d -v $(pwd):/go/src/sensu-sic-handler sensu-sic-handler sleep 3600)"
  - docker exec ${CONTAINER_ID} sh -c 'dep ensure'

script:
  - docker exec ${CONTAINER_ID} sh -c 'cd .. && golint -set_exit_status $(go list sensu-sic-handler/...)'
  - docker exec ${CONTAINER_ID} sh -c 'errcheck ./...'
  - docker exec ${CONTAINER_ID} sh -c 'goconst -ignore=^vendor ./...'
  - docker exec ${CONTAINER_ID} sh -c 'ineffassign ./'
  - docker exec ${CONTAINER_ID} sh -c 'go build -a'

before_script:
  - echo "REPO ${TRAVIS_REPO_SLUG} TAG ${TRAVIS_TAG}"
