version: '3'

services:
  etcd:
    image: bitnami/etcd:3
    volumes:
      - ./.data/etcd:/opt/bitnami/etcd/data
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'

  dev:
    depends_on:
      - etcd
    build:
      context: ./
    volumes:
      - ./:/go/src/sensu-sic-handler/
