[prune]
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/sensu/sensu-go"
  version = "5.7.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-redmine"

[[constraint]]
  branch = "master"
  name = "github.com/bluele/slack"
