[prune]
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "github.com/sensu/sensu-go"
  version = "5.7.0"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.3.13"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-redmine"

[[constraint]]
  branch = "master"
  name = "github.com/bluele/slack"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-xmpp"
